title: Hiker - 行·书
description: > # this means to ignore newlines until "baseurl:"
  Simple FE-Tech Blog<br>
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "https://hiker90.github.io" # the base hostname & protocol for your site, e.g. http://example.com


author:
  name: 'yanhui'
  avatar: '/images/avatar.png'
  github_username:  hiker90  
  email: dreamsontheway@163.com
  logo: '/images/logo.svg'

# Build settings
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge
  
permalink: /:categories/:year/:title.html


